title: Danielle Nemschoff
description: >
  <img src="/headshot_edit.JPG" alt="Profile Image" style="width:200px; height:auto;"> 
theme: jekyll-theme-minimal

# Your details
author:
  name: Danielle Nemschoff
  email: dinemschoff@uchicago.edu

markdown: kramdown

nav_links:
- name: Home
  link: /
- name: Research
  link: /research
- name: Teaching
  link: /teaching

plugins:
- jekyll-seo-tag 


