title: Danielle Nemschoff
description: >
  <img src="/DSC04265.jpg" alt="Profile Image" style="width:150px; height:auto;"> 
theme: jekyll-theme-minimal

# Your details
author:
  name: Danielle Nemschoff
  email: dinemschoff@uchicago.edu

markdown: kramdown

nav_links:
- name: Home
  link: /
- name: Research
  link: /research
- name: Teaching
  link: /teaching


