title: Danielle Nemschoff
description: >
  Hi! I am a PhD student a the University of Chicago Harris School of Public Policy. My areas of focus are labor economics, applied microeconomis and the economics of crime/criminal justice.
theme: minimal

# Your details
author:
  name: Danielle Nemschoff
  email: dinemschoff@uchicago.edu
